[project]
name = "track-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Evandro", email = "evandroivandro65@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[tool.fastapi]
entrypoint = "track_flow.main:app"

[project.scripts]
track-flow = "track_flow:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
